apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.ServiceName }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ .Values.ServiceName }}
    minReplicas: {{ .Values.ReplicaCount }}
    maxReplicas: {{ .Values.MaxReplicaCount }}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
status:
    observedGeneration: 1